-- Language: MySQL

-- Japanese Cities' Attributes
SELECT * FROM CITY WHERE COUNTRYCODE='JPN';

-- Japanese Cities' Names
SELECT NAME FROM CITY WHERE COUNTRYCODE = 'JPN';

-- African Cities
SELECT CITY.NAME FROM CITY
    INNER JOIN COUNTRY
    ON CITY.COUNTRYCODE = COUNTRY.CODE
WHERE COUNTRY.CONTINENT = 'Africa';

-- Average Population of Each Continent
SELECT COUNTRY.CONTINENT, FLOOR(AVG(CITY.POPULATION)) AS AVG_POPULATION FROM COUNTRY
INNER JOIN CITY ON
COUNTRY.CODE = CITY.COUNTRYCODE
GROUP BY COUNTRY.CONTINENT
ORDER BY AVG_POPULATION DESC;
