-- Language: MySQL

-- Average Population
SELECT ROUND(AVG(POPULATION)) FROM CITY;

-- Japan Population
SELECT SUM(POPULATION) FROM CITY
    WHERE COUNTRYCODE = 'JPN';

-- Population Density Difference
SELECT MAX(POPULATION)-MIN(POPULATION) FROM CITY;

-- Population Census
SELECT SUM(CITY.POPULATION) FROM CITY
    INNER JOIN COUNTRY
    ON CITY.COUNTRYCODE = COUNTRY.CODE
WHERE COUNTRY.CONTINENT = 'Asia';
